name: Azure Login and Hello World

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  azure_login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Ensure GitHub can write an id-token for Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Sample hello world command after login
      - name: Run Hello World
        run: echo "Hello, World!"


