name: Azure Login 

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  azure_login:
    runs-on: ubuntu-latest
    env:
      AZURE_CONTAINER_REGISTRY: devopsdemoregistry
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
          
      # Ensure GitHub can write an id-token for Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      
       # Step 2: Login to Azure Container Registry (ACR)
      - name: Azure Container Registry Login
        run: |
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

      # Build docker image
      - name: Verify Docker Installation
        run: |
          docker --version

      - name: Pull Nginx Docker Image
        run: |
          docker pull nginx:latest

      # Tag the Nginx image for ACR
      - name: Tag Docker Image
        run: |
          docker tag nginx:latest ${{ env.AZURE_CONTAINER_REGISTRY }}/nginx:latest

      # Push the tagged Nginx image to ACR
      - name: Push Docker Image to ACR
        run: |
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/nginx:latest
 


