name: Azure Login 

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  azure_login:
    runs-on: ubuntu-latest
    env:
      AZURE_CONTAINER_REGISTRY: devopsdemoregistry
      CONTAINER_APP_NAME: appcontainerdemo
      RESOURCE_GROUP: Azure-project
      REGION: eastus
      VNET_NAME: demovnet
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
          
      # Ensure GitHub can write an id-token for Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      
       # Step 2: Login to Azure Container Registry (ACR)
      - name: Azure Container Registry Login
        run: |
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

      # Build docker image
      - name: login to registry through token
        run: |
          docker login -u github -p ${{ secrets.REGISTRY_TOKEN }} devopsdemoregistry.azurecr.io

      - name: Pull Nginx Docker Image
        run: |
          docker pull nginx:latest

      # Tag the Nginx image for ACR
      - name: Tag Docker Image
        run: |
          docker tag nginx:latest devopsdemoregistry.azurecr.io/nginx:latest

      # Push the tagged Nginx image to ACR
      - name: Push Docker Image to ACR
        run: |
          docker push devopsdemoregistry.azurecr.io/nginx:latest


      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
          --name appcontainerdemo \
          --resource-group Azure-project \
          --image ${{ env.AZURE_CONTAINER_REGISTRY }}/nginx:latest \
 


